### PR TITLE
[#92] [Bug] Application crashing on entering Coins Detail second time

### LINKED ISSUE #92: Fix: Application crashing on entering Coins Detail second time
## Issue

Application is crashing on second attempt of entering `Detail Screen`.

https://user-images.githubusercontent.com/32578035/216288358-cc4c5ea2-2017-4ab8-96ce-1478034a83dc.mov

## Expected

Application should not crash when we enter `Detail Screen`.

## Steps to reproduce

1. Go to `Home Screen`
2. Click on any coin to go to `Detail Screen`
3. Go back
4. Click on the same coin to to `Detail Screen`

### PR DESCRIPTION
**Pull request by kaungkhantsoe**
- #92 

## What happened 👀

Application crashing with `NoSuchElementException` on second attempt and on forward of entering the Coin Detain screen.

## Insight 📝

- Fetching and mapping `LineChartData` from coin prices takes some time and trying to get the `maxPrice`, `minPrice`, `maxPriceIndex` and `minPriceIndex` during that time cause the exception.
- Checking the size of `points` in `LineChartData` fixed the issue.

## Proof Of Work 📹

https://user-images.githubusercontent.com/32578035/216512649-c8097b43-2e7c-49fe-8624-a369ff25b9f8.mov

### CODE REVIEW

File: app/src/main/java/co/nimblehq/compose/crypto/ui/components/linechart/CoinPriceChart.kt [hunk 1]
```diff
@@ -84,37 +86,39 @@ fun CoinPriceChart(
                 )
             )
 
-            val maxPrice = lineChartData.points.maxOf { it.value }
-            val minPrice = lineChartData.points.minOf { it.value }
-            val maxPriceIndex = lineChartData.points.indexOfFirst { it.value == maxPrice }
-            val minPriceIndex = lineChartData.points.indexOfFirst { it.value == minPrice }
+            if (lineChartData.points.isNotEmpty()) {
```
Comment (luongvo) [inline app/src/main/java/co/nimblehq/compose/crypto/ui/components/linechart/CoinPriceChart.kt:89]: 👍

**Review by luongvo — APPROVED** [review]

**Review by doannimble — APPROVED** [review]

**Review by Wadeewee — APPROVED** [review]
